CREATE DATABASE IF NOT EXISTS m5_forecasting;
USE DATABASE m5_forecasting;

CREATE OR REPLACE WAREHOUSE m5_de_wh 
    WITH WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE;

USE WAREHOUSE m5_de_wh;

CREATE SCHEMA IF NOT EXISTS raw;          
CREATE SCHEMA IF NOT EXISTS analytics;    
CREATE SCHEMA IF NOT EXISTS feature_store;
CREATE SCHEMA IF NOT EXISTS monitoring;